e2eTest: &e2eTest
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/giantswarm/aws-operator
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Get e2ectl binary
        command: |
          wget -q $(curl -sS https://api.github.com/repos/giantswarm/e2ectl/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
          chmod +x ./e2ectl
    - run:
        name: Init cluster
        command: |
          ./e2ectl cluster create
          cp $(./e2ectl kubeconfig path) ${E2E_TEST_DIR}/kubeconfig
    - run:
        name: Run test
        command: |
          docker run --rm --network host \
            -v $(pwd)/${E2E_TEST_DIR}:/e2e \
            -v $(pwd):/go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
            -e E2E_KUBECONFIG=/e2e/kubeconfig \
            -e AWS_API_HOSTED_ZONE_GUEST=${AWS_API_HOSTED_ZONE_GUEST} \
            -e AWS_INGRESS_HOSTED_ZONE_GUEST=${AWS_INGRESS_HOSTED_ZONE_GUEST} \
            -e AWS_REGION=${AWS_REGION} \
            -e CATALOGBOT_SSH_KEY_PRIVATE_BASE64=${CATALOGBOT_SSH_KEY_PRIVATE_BASE64} \
            -e COMMON_DOMAIN=${COMMON_DOMAIN} \
            -e DEPLOYMENT_EVENTS_TOKEN=${DEPLOYMENT_EVENTS_TOKEN} \
            -e GITHUB_BOT_TOKEN=${GITHUB_BOT_TOKEN} \
            -e GUEST_AWS_ACCESS_KEY_ID=${GUEST_AWS_ACCESS_KEY_ID} \
            -e GUEST_AWS_ARN=${GUEST_AWS_ARN} \
            -e GUEST_AWS_SECRET_ACCESS_KEY=${GUEST_AWS_SECRET_ACCESS_KEY} \
            -e HOST_AWS_ACCESS_KEY_ID=${HOST_AWS_ACCESS_KEY_ID} \
            -e HOST_AWS_SECRET_ACCESS_KEY=${HOST_AWS_SECRET_ACCESS_KEY} \
            -e REGISTRY_PULL_SECRET=${REGISTRY_PULL_SECRET} \
            -e RELEASE_TOKEN=${RELEASE_TOKEN} \
            -e STORMFORGER_API_TOKEN=${STORMFORGER_API_TOKEN} \
            -e CIRCLE_SHA1=${CIRCLE_SHA1} \
            -e GITHUB_BOT_TOKEN=${GITHUB_BOT_TOKEN} \
            -e E2E_TESTED_VERSION=${E2E_TESTED_VERSION} \
            -e VAULT_TOKEN=mytoken \
            -w /go/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} \
            golang:1 go test -v -timeout 7200s -tags k8srequired ./${E2E_TEST_DIR}/
    - run:
        name: Export logs
        command: |
          ./e2ectl logs export --logs-dir=kind/logs
        when: always
    - store_artifacts:
        path: kind/logs
        destination: logs
    - run:
        name: Finish with teardown
        command: ./e2ectl cluster delete
        when: always

orbs:
  architect: giantswarm/architect@0.4.3

version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version

    - run: |
        date +"%Y" > /tmp/year
        date +"%m" > /tmp/month
        date +"%d" > /tmp/day
    - restore_cache:
        keys:
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}

    - run: ./architect build

    - store_test_results:
        path: /tmp/results

    - save_cache:
        key: go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        paths:
        - /tmp/go/cache

    - persist_to_workspace:
        root: .
        paths:
        - ./aws-operator

    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            ./architect deploy
          fi

  master:
    docker:
      - image: busybox
    steps:
      - run: "true"
  pr:
    docker:
      - image: busybox
    steps:
      - run: "true"



  e2eTestCurPRClusterState:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/clusterstate"
    <<: *e2eTest

  e2eTestCurMasterClusterState:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/clusterstate"
    <<: *e2eTest

  e2eTestWIPPRClusterState:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/clusterstate"
    <<: *e2eTest

  e2eTestWIPMasterClusterState:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/clusterstate"
    <<: *e2eTest



  e2eTestCurPRDraining:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/draining"
    <<: *e2eTest

  e2eTestCurMasterDraining:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/draining"
    <<: *e2eTest

  e2eTestWIPPRDraining:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/draining"
    <<: *e2eTest

  e2eTestWIPMasterDraining:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/draining"
    <<: *e2eTest



# e2eTestCurPRIPAM:
#   environment:
#     E2E_TESTED_VERSION: "current"
#     E2E_TEST_DIR: "integration/test/ipam"
#   <<: *e2eTest
#
# e2eTestCurMasterIPAM:
#   environment:
#     E2E_TESTED_VERSION: "current"
#     E2E_TEST_DIR: "integration/test/ipam"
#   <<: *e2eTest
#
# e2eTestWIPPRIPAM:
#   environment:
#     E2E_TESTED_VERSION: "wip"
#     E2E_TEST_DIR: "integration/test/ipam"
#   <<: *e2eTest
#
# e2eTestWIPMasterIPAM:
#   environment:
#     E2E_TESTED_VERSION: "wip"
#     E2E_TEST_DIR: "integration/test/ipam"
#   <<: *e2eTest



  e2eTestCurPRRecreateCluster:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/recreatecluster"
    <<: *e2eTest

  e2eTestCurMasterRecreateCluster:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/recreatecluster"
    <<: *e2eTest

  e2eTestWIPPRRecreateCluster:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/recreatecluster"
    <<: *e2eTest

  e2eTestWIPMasterRecreateCluster:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/recreatecluster"
    <<: *e2eTest



  e2eTestCurPRScaling:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/scaling"
    <<: *e2eTest

  e2eTestCurMasterScaling:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/scaling"
    <<: *e2eTest

  e2eTestWIPPRScaling:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/scaling"
    <<: *e2eTest

  e2eTestWIPMasterScaling:
    environment:
      E2E_TESTED_VERSION: "wip"
      E2E_TEST_DIR: "integration/test/scaling"
    <<: *e2eTest



  # Note we only have update tests for the current version because it anyway
  # tests one version transition. Having the same tests for WIP only runs the
  # same test twice and we can simply save resources by not doing so.
  e2eTestCurMasterUpdate:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/update"
    <<: *e2eTest
  e2eTestCurPRUpdate:
    environment:
      E2E_TESTED_VERSION: "current"
      E2E_TEST_DIR: "integration/test/update"
    <<: *e2eTest



workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          name: push-aws-operator-to-docker
          image: "quay.io/giantswarm/aws-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: push-aws-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-operator"
          requires:
            - push-aws-operator-to-docker
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-to-aws-app-collection
          app_name: "aws-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-aws-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - hold:
          type: approval
      - master:
          requires:
            - build
          filters:
            branches:
              only: master
      - pr:
          requires:
            - build
            - hold
          filters:
            branches:
              ignore: master



#     - e2eTestCurMasterClusterState:
#         requires:
#           - master
#     - e2eTestWIPMasterClusterState:
#         requires:
#           - master
      - e2eTestCurPRClusterState:
          requires:
            - pr
      - e2eTestWIPPRClusterState:
          requires:
            - pr



#     - e2eTestCurMasterDraining:
#         requires:
#           - master
#     - e2eTestWIPMasterDraining:
#         requires:
#           - master
      - e2eTestCurPRDraining:
          requires:
            - pr
      - e2eTestWIPPRDraining:
          requires:
            - pr



#     - e2eTestCurMasterIPAM:
#         requires:
#           - master
#     - e2eTestWIPMasterIPAM:
#         requires:
#           - master
#     - e2eTestCurPRIPAM:
#         requires:
#           - pr
#     - e2eTestWIPPRIPAM:
#         requires:
#           - pr



#     - e2eTestCurMasterRecreateCluster:
#         requires:
#           - master
#     - e2eTestWIPMasterRecreateCluster:
#         requires:
#           - master
      - e2eTestCurPRRecreateCluster:
          requires:
            - pr
      - e2eTestWIPPRRecreateCluster:
          requires:
            - pr



#     - e2eTestCurMasterScaling:
#         requires:
#           - master
#     - e2eTestWIPMasterScaling:
#         requires:
#           - master
      - e2eTestCurPRScaling:
          requires:
            - pr
      - e2eTestWIPPRScaling:
          requires:
            - pr



#     - e2eTestCurMasterUpdate:
#         requires:
#         - master
      - e2eTestCurPRUpdate:
          requires:
          - pr
